### PR TITLE
warning that rocm is only supported on linux hosts

### PR DESCRIPTION
**Pull request by AuroraNemoia**
This should avoid users spending hours setting SD up only to hit a roadblock.

### CODE REVIEW

**Comment by fractal-fumbler** [comment]
suppose it's better to create separate yalm configuration file for amd installation
for example: add to pip section
```ini
name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
#  - cudatoolkit=11.3
#  - pytorch=1.11.0
#  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/rocm5.1.1
    - torch
    - torchvision
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
```
`#  - cudatoolkit=11.3`
`#  - pytorch=1.11.0`
`#  - torchvision=0.12.0`
just to show what was before

**Comment by neonsecret** [comment]
actually I heard docker is supported on windows too
I'm yet to test it

**Comment by AuroraNemoia** [comment]
image

and [this issue about ROCm support under WSL2](https://github.com/RadeonOpenCompute/ROCm/issues/794) (Which Docker uses when possible)

**Comment by neonsecret** [comment]
soo

nice

**Comment by fractal-fumbler** [comment]
hello :)

on reddit found guide for rocm on windows 
https://rentry.org/ayymd-stable-diffustion-v1_4-guide

**Comment by neonsecret** [comment]
> hello :)
> 
> on reddit found guide for rocm on windows https://rentry.org/ayymd-stable-diffustion-v1_4-guide

yeah because it's a cpu one lol

> hello :)
> 
> on reddit found guide for rocm on windows https://rentry.org/ayymd-stable-diffustion-v1_4-guide

oh, I will have a look

**Comment by GitHub1712** [comment]
runs fine on windows

**Comment by Enferlain** [comment]
Anyone see anything new since? Was trying to get docker to work but yeah seems it's only for Linux.

**Pull request closed without merging**
